development: &development

  gis:
    url: "https://2gis.ru"
    style:
      header_title: ".miniCard__headerTitle"
      result: ".searchResults__headerName"
      name: ".cardHeader__headerNameText"
      phone: ".contact__phonesItemLinkNumber"
      site: "div.contact__websites a"

  redis:
    url: "redis://localhost:6379/0"
    timeout: 10
    thread_safe: true

  yandex:
    url: "https://yandex.ru/search/xml?user=andrei-miraklinoff&key=03.256072755:a0d2d02457627bd74072bfd4e6b03a17"
    mirror_1: "http://0s.pfqw4zdfpaxhe5i.cmle.ru"
    mirror_2: "http://0s.pfqw4zdfpaxhe5i.nblz.ru"
